import { toggleElement } from "../functions/toggleElement";

function HelpSidebar() {
  return (
    <>
      <div id="helpSidebar" className="border sidePanel panel hover scroll">
        <p className="sidebarHeader">=== HELP ===</p>
        <div>
          <div
            className="sectionToggler border"
            onClick={() => toggleElement("helpReadme")}
          >
            <p> READ ME! </p>
          </div>
          <div id="helpReadme" className="blockText">
            <p>
              Yo! Regina told me you were new to the world of netrunning and
              wanted to get your feet wet, well not actually wet - that'll come
              later, much later. Anyway, real lucky for you that I owe her a
              favor. I set up this virtual machine for you to get the basics
              down, to stretch your cyber-legs. It's not much, not compared to -
              like - the new Raven micro-processors or whatever. But... when you
              fuck up - and you will fuck up - TraumaTeam won't be barging down
              your door to carry your braindead body to hospital or worse.
            </p>
            <p>
              To save us both a lot of hassle this machine only runs in RAM.
              Nothing is stored cept your username, session id and and notes you
              make. So don't reload the page unless you've really messed
              something up and wanna reset. Any super burning questions, hit me
              up on irc - but plx try to work it out yourself first, k. If you
              can't work out how to get to irc, you're a lost cause. Tell Regina
              I did her good!
            </p>
            <p>
              <em> - shade </em>
            </p>
            <p>
              Oh and first bit of advice to get you started. type "cmds" into
              the command line, hit enter and you'll get a list of all the
              commands you can use. put a --help after a command an it'll tell
              you what it does. Figure the rest out yourself.{" "}
            </p>
          </div>
        </div>
        {/*/////////////////////////////////// GLOSSARY ////////////////////////////////////////////*/}
        <div
          className="sectionToggler border"
          onClick={() => toggleElement("helpGlossary")}
        >
          <p>glossary</p>
        </div>
        <div
          id="helpGlossary"
          className="blockText"
          style={{ display: "none" }}
        >
          <p>
            Its a big wide world out there. Can't be expected to know
            everything. That's what data storage is for.
          </p>
          {/*///////////////////////////*/}
          <p
            className="sidebarSubsection hover"
            onClick={() => toggleElement("ircInfo")}
          >
            IRC
          </p>
          <p id="ircInfo" style={{ display: "none" }}>
            IRC stands for Internet Relay Chat. Also kinda known as a BBS or
            Bulletin Board System. There's a difference, but like whatever.
            Close enough. An IRC is a server somewhere that a bunch of people
            sign into to send messages, to each other. I've already added you to
            one I'm in. 7th-Circle. Drop me a message there if you get hella
            stuck
          </p>
          {/*///////////////////////////*/}
          <p
            className="sidebarSubsection hover"
            onClick={() => toggleElement("netrunnerInfo")}
          >
            Netrunner
          </p>
          <div id="netrunnerInfo" style={{ display: "none" }}>
            <p>
              You'd better already know this or you're kinda fucked. Just in
              case tho. A netrunner is basically just a very skilled user of
              computers and net tech. Most of us have specialised cyberware for
              the rapid ingest, analysis and exporting of data. Me, I've got a
              Biotech Sigma Mk.2 cyberdeck, which is basically a brain computer
              interface (BCI) on mega-steroids. I've also got a custom suit with
              vanadium-titanium-kevlar composite heat pipes to extract the heat
              generated by by cyberware and dissipate it into the bath of ice i
              conduct my business from.
            </p>
            <p>
              The most well equipped netrunners tend to work for corps like
              Arasaka, Zetatech or Netwatch, but there are plenty of us left
              with an intact soul and an edge. If you're decked out in chrome be
              careful around netrunners. They could disable or break your
              cyberware in a mircosec. Or worse, if you've got some wetware in
              your brain, they can overvolt it so much that your brain literally
              boils inside your skull. In fact, brain boilers are the leading
              cause of death for netrunners.
            </p>
          </div>
          {/*///////////////////////////*/}
          <p
            className="sidebarSubsection hover"
            onClick={() => toggleElement("netwatchInfo")}
          >
            NetWatch
          </p>
          <p id="netwatchInfo" style={{ display: "none" }}>
            Ever heard of a thing called the Blackwall. ~~~ Spooooooky ~~~. A
            big shield to keep all those nasty rogue, pre-war AI's at bay. The
            grand picket fence of cyberspace! Just so happens that if you have
            the eddies, Netwatch'll patrol your little section of that fence.
            And hey, if they happen to take a peek at whatever data is flowing
            around there, that's just a happy coincidence. It's not like knowing
            the inside business of anyone and everyone with a couple of eddies a
            lucrative opportunity for state sanctioned skullduggery. But
            never-you-mind that it literally says protected by Netwatch at the
            bottom of your screen. I took care of that for ya. Just left the
            message to keep you on your toes.
          </p>
          {/*///////////////////////////*/}
          <p
            className="sidebarSubsection hover"
            onClick={() => toggleElement("sshInfo")}
          >
            SSH
          </p>
          <p id="sshInfo" style={{ display: "none" }}>
            SSH means secure shell... i dunno why the h is there tbh. Basically,
            it just lets you log into another machine through the wire. A shell
            is what you're using now, simple command line tools an whatnot.
          </p>
          <p
            className="sidebarSubsection hover"
            onClick={() => toggleElement("zombieInfo")}
          >
            Z.O.M.B.I.E
          </p>
          <div id="zombieInfo" style={{ display: "none" }}>
            <p>
              Zetatech Online Machine Buffered Information Environment or ZOMBIE
              is what you're using right now. A small server, and operating
              system all of its own. A little more sophisticated than a shell,
              soooooo much less sophisticated than a proper netrunners wetware.
              But hey, at least with the zombie there's no risk of literally
              dying when some psycho chairjock blasts your brain with daemons
              designed to kill.
            </p>
            <p>
              This particular incarnation is one I have customised for ya. So
              netwatch dont see all the failures you're gonna make and then can
              laugh their asses of before throwing you in prison. ur welcome
              choom. There's no persistent storage. Pain in the dick I know, but
              trust me, I'm doin us both a massive favour. Whatever tech ur
              using to access the zombie should remember your credentials tho,
              but that's it. Nada. So don't reload unless you really fuck
              something up.
            </p>
          </div>
        </div>

        {/*/////////////////////////////////// MAP ////////////////////////////////////////////*/}
        <div
          className="sectionToggler border"
          onClick={() => toggleElement("helpMap")}
        >
          <p> map </p>
        </div>

        <div id="helpMap" className="blockText" style={{ display: "none" }}>
          <p>
            There's a task for you within the files of this VM. Something to
            test and prove yourself with. This datamap should be useful for that
            task.
          </p>
          <p>
            -<em>Shade</em>
          </p>
          <span style={{ fontFamily: "monospace" }}>
            ├── <strong>bbs_mask_0Hp8BAZ8gkF8</strong>
            <br />
            │ └── permission denied <br />
            ├── <strong>bbs_mask_2mGUUHfQIk0t</strong>
            <br />
            │ └── permission denied
            <br />
            ├── <strong> bbs_mask_9SOCqTxfm2Z</strong>
            <br />
            │ ├── 91E0C5NMg5xE
            <br />
            │ ├── HjTESlk7aw4b
            <br />
            │ ├── M9KFZKUlring
            <br />│ ├── <strong>p7FzTKa13OhG</strong>
            <br />
            │ │ ├── ruleset
            <br />
            │ │ ├── ufw.conf.d
            <br />│ │ └── <strong>whitelist</strong>
            <br />
            │ │ | ├── jeon-kiri
            <br />
            │ │ | ├── leon
            <br />
            │ │ | ├── maman-briggite
            <br />
            │ │ | ├── moseley
            <br />
            │ │ | ├── mr-hands
            <br />
            │ │ | ├── placide
            <br />
            │ │ | └── ti-neptune
            <br />
            │ └── saoXGjvToAlh
            <br />
            ├── <strong>bbs_mask_hMlMhTNGxi05</strong>
            <br />
            │ └── permission denied
            <br />
            ├── <strong>bbs_mask_XpPkmHxDgPfN</strong>
            <br />
            │ └── permission denied
            <br />
            └── <strong>root</strong>
            <br />
            | └── permission denied
            <br />
          </span>
        </div>
      </div>
    </>
  );
}

export default HelpSidebar;
